var GAME_LEVELS = [
  ["                                                                    y           ",
   "                                                                    y           ",
   "                                                        o           y           ",
   "                                                                    y           ",
   "                                             |                     oy           ",
   "                                                                    y           ",
   "                                                                  yyy           ",
   "                                                   yyy     yyyy   y             ",
   "                                    o o     yyy               y!!!y             ",
   "                                                              yyyyy             ",
   "                          yyy      yyyyy                                        ",
   "                                                  yyy                    xxxxx  ",
   "  xx                                      o o                                x  ",
   "  x                     o                                yy                  x  ",
   "  x                yyy          xxx      yyyyy          yyyy  |    o     | o x  ",
   "  x                     o         x                                          x  ",
   "  x  @                            x                              xxxxx       x  ",
   "  xxxxxxxx      xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "         x      x             x   x                  x     x                    ",
   "         x!!!!!!x             x!!!x                  x!!!!!x                    ",
   "         x!!!!!!x             x!!!x                  x!!!!!x                    ",
   "         xxxxxxxx             xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "             x                                                               x  ",
   "             x          |       |                                            x  ",
   "             x                                                o              x  ",
   "             x   o                                                           x  ",
   "             x              |       |                 o      yyy             x  ",
   "             xyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                              o  x  ",
   "             x                             yyyy  |   yyy                     x  ",
   "             x                             y                            yyyyyx  ",
   "             x       o                     y o                        yyyyyyyx  ",
   "             x     yyyyy                   yyyyyyyyyyyyyyyyy      o          x  ",
   "  xx         xo        y                   yyyyyvyyyyyyyvyyyyyy              x  ",
   "  x          xx        y     |       |                        yyyy           x  ",
   "  x          xxx       y  O      O                            yyyyyyy        x  ",
   "  x                    y  o      o                  o                        x  ",
   "  x  @                 y                                                     x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                   xxxxxxxxxxx  ",
   "                                                                   xxxxxxxxxxx  ",
   "                                                                   xxxxxxxxxxx  ",
   "                                                                   xxxxxxxxxxx  ",
   "                                                                   xxxxxxxxxxx  ",
   "                                                                   xxxxxxxxxxx  ",
   "                     o                                 o           xxvxxvxxxxx  ",
   "  xx                              o                                          x  ",
   "  x           o      y                           o     y                     x  ",
   "  x                              yyy                                         x  ",
   "  x          yyy           o               o    yyy                       o  x  ",
   "  x  @                                                                       x  ",
   "  xxxxxxxx                 y               y               xxxxxxxxxxxxxxxxxxx  ",
   "         x                                                 x                    ",
   "         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  x                                                                          x  ",
   "  x      |              |                                                    x  ",
   "  x                                                                          x  ",
   "  x                |               |      |                                   x  ",
   "  x   o                      o                o                o             x  ",
   "  x           |                                    |      |                  x  ",
   "  xyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy            x  ",
   "  x                                                             yyy  o       x  ",
   "  x                                                                          x  ",
   "  x                  o                                  o           yyy      x  ",
   "  x                               o                                          x  ",
   "  x           o      y                           o     yyy                  xx  ",
   "  x                             yyyyy                                     o  x  ",
   "  x          yyy           o               o    yyy                          x  ",
   "  x  @                                                       yyyy    xxxxxxxxx  ",
   "  xxxxxxxx                 y               y                                 x  ",
   "         x                                                                   x  ",
   "         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  x                                                                          x  ",
   "  x                     |       |                                            x  ",
   "  x                                                           o              x  ",
   "  x              o                        |                                  x  ",
   "  x                         |       |                 o      yyy             x  ",
   "  x          xyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                              o  x  ",
   "  x          x                  y          yyyy  |   yyy                     x  ",
   "  x          x                  y     o    y                            yyyyyx  ",
   "  x          x       o          y          y o                        yyyyyyyx  ",
   "  xoooooooooox     yyyyy        y     y    yyyyyyyyyyyyyyyyy      o          x  ",
   "  xoooooooooox         y        yy    y    yyyyyvyyyyyyyvyyyyyy              x  ",
   "  xooooooooooxxx       y        y     y                       yyyy           x  ",
   "  xxxxxxxxxxxxvxx      y        y     y                       yyyyyyyy   |   x  ",
   "  x            x       y        y  o  y     |         |         |   y        x  ",
   "  x  @         x   o   y        y  | yy                             y       xx  ",
   "  xxxxx        x   |  yy        y     y                             y o      x  ",
   "      x        x       y    |   y     y                             y        x  ",
   "      x    |   x       y        y  o  y                             yyy      x  ",
   "      x        xx      y        yy    y     |    o    |    o    |           xx  ",
   "      x o          o   y              y                                      x  ",
   "      x                y    o         y                                      x  ",
   "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  "]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
